services:
  worker-A:
    image: decentralized-llm-thesis:latest
    command: python server/server.py
    # command: python -Xfrozen_modules=off -m debugpy --listen 0.0.0.0:5678 server/server.py
    # command: sleep infinity
    hostname: worker-A
    environment:
      - MODEL_PATH=/${MODEL_PATH}
      - GRPC_PORT=5001
      - NUM_LAYERS=$NUM_LAYERS
      # - NUM_LAYERS=10
      - PROFILE=$PROFILE
      - QUANTIZE=$QUANTIZE
      - LOG_LEVEL=$LOG_LEVEL
    volumes:
      - ./models:/models:ro 
    deploy:
      resources:
        # reservations:
        #   devices:
        #     - driver: nvidia
        #       count: 1
        #       capabilities: [gpu]
        limits:
          memory: 3.5G 
          # cpus: '8.0'
    ports:
      - "5671:5678"

  worker-B:
    image: decentralized-llm-thesis:latest
    command: python server/server.py
    # command: python -Xfrozen_modules=off -m debugpy --listen 0.0.0.0:5678 server/server.py
    # command: sleep infinity
    hostname: worker-B
    environment:
      - MODEL_PATH=/${MODEL_PATH}
      - GRPC_PORT=5001
      - NUM_LAYERS=$NUM_LAYERS
      # - NUM_LAYERS=10
      - PROFILE=$PROFILE
      - QUANTIZE=$QUANTIZE
      - LOG_LEVEL=$LOG_LEVEL
      # - ADDED_DELAY=0.08
      - BOOTSTRAP_NODE_ADDR=worker-A:5001
    volumes:
      - ./models:/models:ro 
    deploy:
      resources:
      #   reservations:
      #     devices:
      #       - driver: nvidia
      #         count: 1
      #         capabilities: [gpu]
        limits:
          memory: 4G # 2.2
          # cpus: '8.0'
    ports:
      - "5672:5678"  

  worker-C:
    image: decentralized-llm-thesis:latest
    command: python server/server.py
    # command: python -Xfrozen_modules=off -m debugpy --listen 0.0.0.0:5678 server/server.py
    # command: sleep infinity
    hostname: worker-C
    environment:
      - MODEL_PATH=/${MODEL_PATH}
      - GRPC_PORT=5001
      - NUM_LAYERS=$NUM_LAYERS
      # - NUM_LAYERS=2
      - PROFILE=$PROFILE
      # - PROFILE=1
      - QUANTIZE=$QUANTIZE
      - LOG_LEVEL=$LOG_LEVEL
      # - ADDED_DELAY=0.08
    volumes:
      - ./models:/models:ro
    deploy:
      resources:
        reservations:
            devices:
              - driver: nvidia
                count: 1
                capabilities: [gpu]
        limits:
          memory: 2G
          # cpus: '6.0'
    ports:
      - "5673:5678"

  worker-D:
    image: decentralized-llm-thesis:latest
    command: python server/server.py
    # command: python -Xfrozen_modules=off -m debugpy --listen 0.0.0.0:5678 server/server.py
    # command: sleep infinity
    hostname: worker-D
    environment:
      - MODEL_PATH=/${MODEL_PATH}
      - GRPC_PORT=5001
      - NUM_LAYERS=$NUM_LAYERS
      # - NUM_LAYERS=2
      - PROFILE=$PROFILE
      # - PROFILE=1
      - QUANTIZE=$QUANTIZE
      - LOG_LEVEL=$LOG_LEVEL
      # - ADDED_DELAY=0.08
      - BOOTSTRAP_NODE_ADDR=worker-C:5001
    volumes:
      - ./models:/models:ro
    deploy:
      resources:
        # reservations:
        #   devices:
        #     - driver: nvidia
        #       count: 1
        #       capabilities: [gpu]
        limits:
          memory: 4G
          # cpus: '6.0'
    ports:
      - "5674:5678"
  
  worker-E:
    image: decentralized-llm-thesis:latest
    command: python server/server.py
    # command: python -Xfrozen_modules=off -m debugpy --listen 0.0.0.0:5678 server/server.py
    # command: sleep infinity
    hostname: worker-E
    environment:
      - MODEL_PATH=/${MODEL_PATH}
      - GRPC_PORT=5001
      - NUM_LAYERS=$NUM_LAYERS
      # - NUM_LAYERS=2
      - PROFILE=$PROFILE
      - QUANTIZE=$QUANTIZE
      - LOG_LEVEL=$LOG_LEVEL
      # - ADDED_DELAY=0.08
      - BOOTSTRAP_NODE_ADDR=worker-D:5001
    volumes:
      - ./models:/models:ro
    deploy:
      resources:
        # reservations:
        #   devices:
        #     - driver: nvidia
        #       count: 1
        #       capabilities: [gpu]
        limits:
          memory: 2G
    ports:
      - "5675:5678"


  client-A:
    image: decentralized-llm-thesis:latest 
    command: python client_gui.py 
    # command: python distributed_chatbot.py --prompt 'write a long thesis on sharks' --max_new_tokens 250
    # command: python -Xfrozen_modules=off -m debugpy --listen 0.0.0.0:5678 client_gui.py
    # command: sleep infinity 
    hostname: client-A
    environment:
      - MODEL_PATH=/${MODEL_PATH}
      - QUANTIZE=$QUANTIZE
      - LOG_LEVEL=$LOG_LEVEL
      # - GRPC_PORT=5001
      # - HOST_MADDRS=/ip4/0.0.0.0/tcp/0 
      # - BOOTSTRAP_NODE_ADDR=worker-A:5001
      # - BOOTSTRAP_NODE_ADDR=150.140.139.205:5001
    volumes:
      - ./models:/models:ro
      - ./src:/app # To make live changes to the client gui code
    ports:
      - "8080:8080" # NiceGUI
      - "5676:5678"

  client-B:
    image: decentralized-llm-thesis:latest 
    # command: python distributed_chatbot.py --prompt 'write a long thesis on sharks' --max_new_tokens 250
    command: python client_gui.py 
    # command: python -Xfrozen_modules=off -m debugpy --listen 0.0.0.0:5678 client_gui.py
    # command: sleep infinity 
    hostname: client-B
    environment:
      - MODEL_PATH=/${MODEL_PATH}
      - QUANTIZE=$QUANTIZE
      - LOG_LEVEL=$LOG_LEVEL
      # - GRPC_PORT = 5001
      # - HOST_MADDRS=/ip4/0.0.0.0/tcp/0 
      # - BOOTSTRAP_NODE_ADDR=worker-A:5001
    volumes:
      - ./models:/models:ro
      - ./src:/app # To make live changes to the client gui code
    ports:
      - "8081:8080" # NiceGUI
      - "5677:5678"  

