services:
  head-server:
    build: .
    command: python server/server.py
    # command: sleep infinity
    environment:
      - MODEL_PATH=/models/Llama-3.2-1B
      - NUM_LAYERS=8
      - LAYERS_START_IDX=0
      - IS_HEAD=True
      - SUCCESSOR_ADDR=tail-server:50051 # It can resolve 'tail-server' because they are on the same docker network
      - PORT=50051
    volumes:
      - ./models:/models:ro # Mount your local models directory into the container
    ports:
      - "50051:50051" # Expose port for potential external access/debugging
      # - "5678:5678"

  tail-server:
    build: .
    command: python server/server.py
    environment:
      - MODEL_PATH=/models/Llama-3.2-1B
      - NUM_LAYERS=8
      - LAYERS_START_IDX=8
      - IS_HEAD=False
      - SUCCESSOR_ADDR= # No successor, it's the tail
      - PORT=50051
    volumes:
      - ./models:/models:ro
    ports:
      - "50052:50051" # Map container port 50051 to host 50052 to avoid conflict

  client:
    build: .
    command: python docker_test.py 
    # command: sleep infinity
    environment:
      - MODEL_PATH=/models/Llama-3.2-1B
      - HEAD_SERVER_ADDR=head-server:50051
    volumes:
      - ./models:/models:ro
    # ports:
    #   - "5678:5678"
    depends_on: # Wait for servers to be healthy before starting
      - head-server
      - tail-server