"""----- LLM Constants -----"""
GLOBAL_MAX_SEQ_LEN = 8192 #8192 #2048 #4096

"""----- Server and Client Constants -----"""
RESERVED_MEM_MB = 500 #500 # Memory reserved for system overhead

ACTIVE_NODE_TAKEOVER_MULT_THRESHOLD = 4.0

OPPRTUNISTIC_TAKEOVER_MULT_THRESHOLD = 1.5

IMBALANCE_THRESHOLD = 0.2 # 15%

PROFILING_DURATION = 10 # seconds

SERVER_BENCHMARK_RESULTS_PATH = ""

"""----- GRPC Constants -----"""
GRPC_MAX_MSG_SIZE = 100 * 1024 * 1024  # 100 MB

GRPC_MAX_WORKERS = 1

GRPC_CHECK_TIMEOUT = 2
GRPC_REQUEST_TIMEOUT = 5
GRPC_CHANNEL_TIMEOUT = 10
INFERENCE_RESPONSE_TIMEOUT = 20

