# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from core.remote import nodeservice_pb2 as core_dot_remote_dot_nodeservice__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in core/remote/nodeservice_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NodeServiceStub(object):
    """The service definition for a server node in the inference chain.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunLayers = channel.unary_unary(
                '/nodeservice.NodeService/RunLayers',
                request_serializer=core_dot_remote_dot_nodeservice__pb2.InferenceRequest.SerializeToString,
                response_deserializer=core_dot_remote_dot_nodeservice__pb2.InferenceResponse.FromString,
                _registered_method=True)
        self.GetPeerMultiaddr = channel.unary_unary(
                '/nodeservice.NodeService/GetPeerMultiaddr',
                request_serializer=core_dot_remote_dot_nodeservice__pb2.Empty.SerializeToString,
                response_deserializer=core_dot_remote_dot_nodeservice__pb2.MultiaddrResponse.FromString,
                _registered_method=True)
        self.Check = channel.unary_unary(
                '/nodeservice.NodeService/Check',
                request_serializer=core_dot_remote_dot_nodeservice__pb2.Empty.SerializeToString,
                response_deserializer=core_dot_remote_dot_nodeservice__pb2.Empty.FromString,
                _registered_method=True)
        self.Reallocate = channel.unary_unary(
                '/nodeservice.NodeService/Reallocate',
                request_serializer=core_dot_remote_dot_nodeservice__pb2.ReallocateRequest.SerializeToString,
                response_deserializer=core_dot_remote_dot_nodeservice__pb2.Empty.FromString,
                _registered_method=True)


class NodeServiceServicer(object):
    """The service definition for a server node in the inference chain.
    """

    def RunLayers(self, request, context):
        """Processes a tensor through the node's layers.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPeerMultiaddr(self, request, context):
        """Returns the full P2P multiaddress of the server node.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Check(self, request, context):
        """Used to check if a node's successor is alive
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reallocate(self, request, context):
        """Triggers the layer re-allocation process
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NodeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunLayers': grpc.unary_unary_rpc_method_handler(
                    servicer.RunLayers,
                    request_deserializer=core_dot_remote_dot_nodeservice__pb2.InferenceRequest.FromString,
                    response_serializer=core_dot_remote_dot_nodeservice__pb2.InferenceResponse.SerializeToString,
            ),
            'GetPeerMultiaddr': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPeerMultiaddr,
                    request_deserializer=core_dot_remote_dot_nodeservice__pb2.Empty.FromString,
                    response_serializer=core_dot_remote_dot_nodeservice__pb2.MultiaddrResponse.SerializeToString,
            ),
            'Check': grpc.unary_unary_rpc_method_handler(
                    servicer.Check,
                    request_deserializer=core_dot_remote_dot_nodeservice__pb2.Empty.FromString,
                    response_serializer=core_dot_remote_dot_nodeservice__pb2.Empty.SerializeToString,
            ),
            'Reallocate': grpc.unary_unary_rpc_method_handler(
                    servicer.Reallocate,
                    request_deserializer=core_dot_remote_dot_nodeservice__pb2.ReallocateRequest.FromString,
                    response_serializer=core_dot_remote_dot_nodeservice__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nodeservice.NodeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nodeservice.NodeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NodeService(object):
    """The service definition for a server node in the inference chain.
    """

    @staticmethod
    def RunLayers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nodeservice.NodeService/RunLayers',
            core_dot_remote_dot_nodeservice__pb2.InferenceRequest.SerializeToString,
            core_dot_remote_dot_nodeservice__pb2.InferenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPeerMultiaddr(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nodeservice.NodeService/GetPeerMultiaddr',
            core_dot_remote_dot_nodeservice__pb2.Empty.SerializeToString,
            core_dot_remote_dot_nodeservice__pb2.MultiaddrResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Check(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nodeservice.NodeService/Check',
            core_dot_remote_dot_nodeservice__pb2.Empty.SerializeToString,
            core_dot_remote_dot_nodeservice__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reallocate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nodeservice.NodeService/Reallocate',
            core_dot_remote_dot_nodeservice__pb2.ReallocateRequest.SerializeToString,
            core_dot_remote_dot_nodeservice__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ClientServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReceiveResponse = channel.unary_unary(
                '/nodeservice.ClientService/ReceiveResponse',
                request_serializer=core_dot_remote_dot_nodeservice__pb2.InferenceResponse.SerializeToString,
                response_deserializer=core_dot_remote_dot_nodeservice__pb2.Empty.FromString,
                _registered_method=True)


class ClientServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ReceiveResponse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClientServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReceiveResponse': grpc.unary_unary_rpc_method_handler(
                    servicer.ReceiveResponse,
                    request_deserializer=core_dot_remote_dot_nodeservice__pb2.InferenceResponse.FromString,
                    response_serializer=core_dot_remote_dot_nodeservice__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nodeservice.ClientService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nodeservice.ClientService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ClientService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReceiveResponse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nodeservice.ClientService/ReceiveResponse',
            core_dot_remote_dot_nodeservice__pb2.InferenceResponse.SerializeToString,
            core_dot_remote_dot_nodeservice__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
