# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nodeservice.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'nodeservice.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11nodeservice.proto\x12\x0bnodeservice\"\x07\n\x05\x45mpty\"&\n\x11MultiaddrResponse\x12\x11\n\tmultiaddr\x18\x01 \x01(\t\"\xb7\x01\n\x10InferenceRequest\x12\x13\n\x0btensor_data\x18\x01 \x01(\x0c\x12\x14\n\x0ctensor_shape\x18\x02 \x03(\x03\x12\r\n\x05\x64type\x18\x03 \x01(\t\x12\x1b\n\x13max_returned_tokens\x18\x04 \x01(\x05\x12\x17\n\nseq_length\x18\x05 \x01(\x05H\x00\x88\x01\x01\x12\x16\n\tinput_pos\x18\x06 \x01(\x03H\x01\x88\x01\x01\x42\r\n\x0b_seq_lengthB\x0c\n\n_input_pos\"M\n\x11InferenceResponse\x12\x13\n\x0btensor_data\x18\x01 \x01(\x0c\x12\x14\n\x0ctensor_shape\x18\x02 \x03(\x03\x12\r\n\x05\x64type\x18\x03 \x01(\t2\xa5\x01\n\x0bNodeService\x12L\n\tRunLayers\x12\x1d.nodeservice.InferenceRequest\x1a\x1e.nodeservice.InferenceResponse\"\x00\x12H\n\x10GetPeerMultiaddr\x12\x12.nodeservice.Empty\x1a\x1e.nodeservice.MultiaddrResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nodeservice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=34
  _globals['_EMPTY']._serialized_end=41
  _globals['_MULTIADDRRESPONSE']._serialized_start=43
  _globals['_MULTIADDRRESPONSE']._serialized_end=81
  _globals['_INFERENCEREQUEST']._serialized_start=84
  _globals['_INFERENCEREQUEST']._serialized_end=267
  _globals['_INFERENCERESPONSE']._serialized_start=269
  _globals['_INFERENCERESPONSE']._serialized_end=346
  _globals['_NODESERVICE']._serialized_start=349
  _globals['_NODESERVICE']._serialized_end=514
# @@protoc_insertion_point(module_scope)
