syntax = "proto3";

package nodeservice;

// The service definition for a server node in the inference chain.
service NodeService {
  // Processes a tensor through the node's layers.
  rpc RunLayers(InferenceRequest) returns (Empty) {}

  // Returns the full P2P multiaddress of the server node.
  rpc GetPeerMultiaddr(Empty) returns (MultiaddrResponse) {}

  // Used to check if a node's successor is alive
  rpc Check(Empty) returns (Empty) {}

  // Triggers the layer re-allocation process
  rpc Reallocate(ReallocateRequest) returns (Empty) {}

  // Runs server_node._connect_to_successor()
  rpc UpdateSuccessorStub(Empty) returns (Empty) {}

  // Triggers assigned layers loading on a backup node
  rpc LoadLayers(Empty) returns (Empty) {}

  // Triggers layer unloading on a node
  rpc UnloadLayers(Empty) returns (Empty) {}

  // Makes the server node remove the client's kv cache from memory
  // Also triggers a rebalancing of the memory allocated to the rest of the nodes' kv caches
  rpc RemoveClientKVCache(RemoveClientKVCacheRequest) returns (Empty) {}
}

// The service definition for a client node that receives inference responses form the TAIL node.
service ClientService {
  // Receives the inference response from the tail node and returns an empty message.
  // rpc ReceiveResponse(InferenceResponse) returns (Empty) {}
  rpc ReceiveResponse(InferenceResponse) returns (Empty) {}
}

message Empty {}

message MultiaddrResponse {
    string multiaddr = 1;
}

// The request message containing the tensor and metadata.
message InferenceRequest {
  bytes tensor_data = 1; // The raw bytes of the tensor.
  repeated int32 tensor_shape = 2; 
  string dtype = 3;           

  // Metadata for the inference step
  int32 max_returned_tokens = 4;
  optional int32 seq_length = 5;
  optional int32 input_pos = 6;

  string response_address = 7;

  // For block-wise quantization
  bytes block_scales = 8;
}

// The response message containing the resulting tensor.
message InferenceResponse {
  bytes tensor_data = 1;
  repeated int32 tensor_shape = 2;
  string dtype = 3;  
  
  optional string error_message = 4;

  // float processing_time = 5;

  // For block-wise quantization
  // bytes block_scales = 6;
}

message ReallocateRequest {
  float total_rate = 1;
  int32 start_layer_index = 2;
  optional bytes predecessor_info = 3;
}

message RemoveClientKVCacheRequest {
  string client_id = 1; // The client's address
  int64 new_max_seq_length = 2;
}

