# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: core/remote/nodeservice.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'core/remote/nodeservice.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x63ore/remote/nodeservice.proto\x12\x0bnodeservice\"\x07\n\x05\x45mpty\"&\n\x11MultiaddrResponse\x12\x11\n\tmultiaddr\x18\x01 \x01(\t\"\xe7\x01\n\x10InferenceRequest\x12\x13\n\x0btensor_data\x18\x01 \x01(\x0c\x12\x14\n\x0ctensor_shape\x18\x02 \x03(\x03\x12\r\n\x05\x64type\x18\x03 \x01(\t\x12\x1b\n\x13max_returned_tokens\x18\x04 \x01(\x05\x12\x17\n\nseq_length\x18\x05 \x01(\x05H\x00\x88\x01\x01\x12\x16\n\tinput_pos\x18\x06 \x01(\x03H\x01\x88\x01\x01\x12\x14\n\x0cpartial_rate\x18\x07 \x01(\x02\x12\x18\n\x10response_address\x18\x08 \x01(\tB\r\n\x0b_seq_lengthB\x0c\n\n_input_pos\"\x8f\x01\n\x11InferenceResponse\x12\x13\n\x0btensor_data\x18\x01 \x01(\x0c\x12\x14\n\x0ctensor_shape\x18\x02 \x03(\x03\x12\r\n\x05\x64type\x18\x03 \x01(\t\x12\x1a\n\rerror_message\x18\x04 \x01(\tH\x00\x88\x01\x01\x12\x12\n\ntotal_rate\x18\x05 \x01(\x02\x42\x10\n\x0e_error_message\"B\n\x11ReallocateRequest\x12\x12\n\ntotal_rate\x18\x01 \x01(\x02\x12\x19\n\x11start_layer_index\x18\x02 \x01(\x05\")\n\x0bLoadRequest\x12\r\n\x05start\x18\x01 \x01(\x05\x12\x0b\n\x03\x65nd\x18\x02 \x01(\x05\"%\n\x0cLoadResponse\x12\x15\n\rlayers_loaded\x18\x01 \x01(\x08\x32\xe1\x02\n\x0bNodeService\x12L\n\tRunLayers\x12\x1d.nodeservice.InferenceRequest\x1a\x1e.nodeservice.InferenceResponse\"\x00\x12H\n\x10GetPeerMultiaddr\x12\x12.nodeservice.Empty\x1a\x1e.nodeservice.MultiaddrResponse\"\x00\x12\x31\n\x05\x43heck\x12\x12.nodeservice.Empty\x1a\x12.nodeservice.Empty\"\x00\x12\x42\n\nReallocate\x12\x1e.nodeservice.ReallocateRequest\x1a\x12.nodeservice.Empty\"\x00\x12\x43\n\nLoadLayers\x12\x18.nodeservice.LoadRequest\x1a\x19.nodeservice.LoadResponse\"\x00\x32X\n\rClientService\x12G\n\x0fReceiveResponse\x12\x1e.nodeservice.InferenceResponse\x1a\x12.nodeservice.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'core.remote.nodeservice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=46
  _globals['_EMPTY']._serialized_end=53
  _globals['_MULTIADDRRESPONSE']._serialized_start=55
  _globals['_MULTIADDRRESPONSE']._serialized_end=93
  _globals['_INFERENCEREQUEST']._serialized_start=96
  _globals['_INFERENCEREQUEST']._serialized_end=327
  _globals['_INFERENCERESPONSE']._serialized_start=330
  _globals['_INFERENCERESPONSE']._serialized_end=473
  _globals['_REALLOCATEREQUEST']._serialized_start=475
  _globals['_REALLOCATEREQUEST']._serialized_end=541
  _globals['_LOADREQUEST']._serialized_start=543
  _globals['_LOADREQUEST']._serialized_end=584
  _globals['_LOADRESPONSE']._serialized_start=586
  _globals['_LOADRESPONSE']._serialized_end=623
  _globals['_NODESERVICE']._serialized_start=626
  _globals['_NODESERVICE']._serialized_end=979
  _globals['_CLIENTSERVICE']._serialized_start=981
  _globals['_CLIENTSERVICE']._serialized_end=1069
# @@protoc_insertion_point(module_scope)
