syntax = "proto3";

package nodeservice;

// The service definition for a server node in the inference chain.
service NodeService {
  // Processes a tensor through the node's layers.
  rpc RunLayers(InferenceRequest) returns (InferenceResponse) {}

  // Returns the full P2P multiaddress of the server node.
  rpc GetPeerMultiaddr(Empty) returns (MultiaddrResponse) {}

  // Used to check if a node's successor is alive
  rpc Check(Empty) returns (Empty) {}

  // Triggers the layer re-allocation process
  rpc Reallocate(ReallocateRequest) returns (Empty) {}

  // Triggers asigned layers loading on a backup node
  rpc LoadLayers(Empty) returns (Empty) {}
}

// The service definition for a client node that receives inference responses form the TAIL node.
service ClientService {
  // Receives the inference response from the tail node and returns an empty message.
  rpc ReceiveResponse(InferenceResponse) returns (Empty) {}
}

message Empty {}

message MultiaddrResponse {
    string multiaddr = 1;
}

// The request message containing the tensor and metadata.
message InferenceRequest {
  bytes tensor_data = 1; // The raw bytes of the tensor.
  repeated int64 tensor_shape = 2; 
  string dtype = 3;           

  // Metadata for the inference step
  int32 max_returned_tokens = 4;
  optional int32 seq_length = 5;
  optional int64 input_pos = 6;

  float partial_rate = 7;

  string response_address = 8;
}

// The response message containing the resulting tensor.
message InferenceResponse {
  bytes tensor_data = 1;
  repeated int64 tensor_shape = 2;
  string dtype = 3;  
  optional string error_message = 4;

  float total_rate = 5;
  float processing_time = 6;
}

message ReallocateRequest {
  float total_rate = 1;
  int32 start_layer_index = 2;
}

// message LoadRequest {
//   int32 start = 1;
//   int32 end = 2;
// }

// message LoadResponse {
//   bool layers_loaded = 1;
// }

