# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import nodeservice_pb2 as nodeservice__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in nodeservice_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NodeServiceStub(object):
    """The service definition for a server node in the inference chain.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunLayers = channel.unary_unary(
                '/nodeservice.NodeService/RunLayers',
                request_serializer=nodeservice__pb2.InferenceRequest.SerializeToString,
                response_deserializer=nodeservice__pb2.InferenceResponse.FromString,
                _registered_method=True)
        self.GetPeerMultiaddr = channel.unary_unary(
                '/nodeservice.NodeService/GetPeerMultiaddr',
                request_serializer=nodeservice__pb2.Empty.SerializeToString,
                response_deserializer=nodeservice__pb2.MultiaddrResponse.FromString,
                _registered_method=True)


class NodeServiceServicer(object):
    """The service definition for a server node in the inference chain.
    """

    def RunLayers(self, request, context):
        """Processes a tensor through the node's layers.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPeerMultiaddr(self, request, context):
        """Returns the full P2P multiaddress of the server node.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NodeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunLayers': grpc.unary_unary_rpc_method_handler(
                    servicer.RunLayers,
                    request_deserializer=nodeservice__pb2.InferenceRequest.FromString,
                    response_serializer=nodeservice__pb2.InferenceResponse.SerializeToString,
            ),
            'GetPeerMultiaddr': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPeerMultiaddr,
                    request_deserializer=nodeservice__pb2.Empty.FromString,
                    response_serializer=nodeservice__pb2.MultiaddrResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nodeservice.NodeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nodeservice.NodeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NodeService(object):
    """The service definition for a server node in the inference chain.
    """

    @staticmethod
    def RunLayers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nodeservice.NodeService/RunLayers',
            nodeservice__pb2.InferenceRequest.SerializeToString,
            nodeservice__pb2.InferenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPeerMultiaddr(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nodeservice.NodeService/GetPeerMultiaddr',
            nodeservice__pb2.Empty.SerializeToString,
            nodeservice__pb2.MultiaddrResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
